name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: '${project.version}'
depends: [Vault]
author: iKeirNez
commands:
  build:
    description: Builds a battery using the materials you have in your inventory, if in creative this does not matter
    usage: /<command> battery <size>